'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class P_Movil_Administrar_Imp_ActualizarRegistros

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''BarraNavegacionJQ1_Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel1_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel1_O As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel1_O_Item1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel1_O_Item1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rlstTarea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rlstTarea As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''BarraNavegacionJQ1_Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel2_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel2_O As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel2_O_Item1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel2_O_Item1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rbProgramacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbProgramacion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtFechaProgramacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaProgramacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BarraNavegacionJQ1_Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel3_O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel3_O As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BarraNavegacionJQ1_Panel3_O_Item1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BarraNavegacionJQ1_Panel3_O_Item1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''ddlOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOperador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoPlantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoPlantilla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoLlamada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoLlamada As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFechaInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trRangoXDias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trRangoXDias As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkRangoXDias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRangoXDias As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''TxtDiaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiaInicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDiaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDiaFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkActGenLin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActGenLin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTodaLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTodaLinea As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''imgAgregarLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarLinea As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgEliminarLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEliminarLinea As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgQuitarTodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuitarTodo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''chkServicioOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkServicioOff As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActualizarConceptos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActualizarConceptos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActPrefijos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActPrefijos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trPlantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPlantilla As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''ddlPlantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPlantilla As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkActualizacionDesconocidos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActualizacionDesconocidos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActualizaNumeros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActualizaNumeros As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActualizarCostosDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActualizarCostosDP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chklstTipoCosteo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chklstTipoCosteo As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chkActualizacionAcumumlados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActualizacionAcumumlados As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnGuardarSer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarSer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''imgGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGuardar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLinea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLinea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomEmp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''imgAgregarDialogLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarDialogLinea As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCerrarDialogLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCerrarDialogLinea As Global.System.Web.UI.WebControls.Image
End Class
