'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class P_Movil_Administrar_Adm_NuevaSolicitud

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''tabDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDetalle As Global.VisualSoft.Comun.LibreriaJQ.TabJQ

    '''<summary>
    '''tabDetalleDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDetalleDatos As Global.VisualSoft.Comun.LibreriaJQ.ContenedorTabJQ

    '''<summary>
    '''tabDetallePoliticas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDetallePoliticas As Global.VisualSoft.Comun.LibreriaJQ.ContenedorTabJQ

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfGaleria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGaleria As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodEmpleado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodEmpleadoAutenticado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodEmpleadoAutenticado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodIntEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodIntEmp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPerfilesEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPerfilesEmpleado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSolicitudMultipleEspecialista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSolicitudMultipleEspecialista As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfLineaSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLineaSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodImeiSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodImeiSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAdmin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfJefeArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfJefeArea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodModDisActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodModDisActual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodModDis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodModDis As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCuentaLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCuentaLinea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTipoSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTipoSolicitud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfServicioSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfServicioSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGrupOrigEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGrupOrigEmp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodigoOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodigoOperador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNombreOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNombreOperador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPlanLineaSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPlanLineaSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodPlanSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodPlanSel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSepDecimal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSepDecimal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSepMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSepMiles As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNumDecimales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNumDecimales As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCostoReposicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCostoReposicion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodLinTip_X_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodLinTip_X_User As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsModal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsModal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfDefTipoSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDefTipoSolicitud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsCulminada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsCulminada As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfMostrarAgregarEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMostrarAgregarEmpleado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNumeroIngresado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNumeroIngresado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tdNombreEmpleado1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNombreEmpleado1 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''tdNombreEmpleado2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNombreEmpleado2 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''lblEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpleado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpleado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dvContenedorControlBP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvContenedorControlBP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bpEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bpEmpleado As Global.Common_Controles_BusquedaPrincipal

    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdNombreEmpleado3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNombreEmpleado3 As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''btnBusquedaEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBusquedaEmpleado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgAgregarEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarEmpleado As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlTipoSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoSolicitud As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dvTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvTabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tbSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbSolicitud As Global.VisualSoft.Comun.LibreriaJQ.TabJQ

    '''<summary>
    '''lblMensajeVerificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeVerificacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCreacionEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCreacionEstado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCreacionEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreacionEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEstadoCreacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoCreacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMensajeEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeEstado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnEquiSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEquiSol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAtras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAtras As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSiguiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSiguiente As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnFinalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinalizar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ifGaleria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifGaleria As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''ifSolPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifSolPer As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''lblLineaSel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLineaSel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trServicioSeleccionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trServicioSeleccionado As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblServSeleccionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServSeleccionado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTipoServicio As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trServicio As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblNuevoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNuevoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trIlimitado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trIlimitado As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkIlimitado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIlimitado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCantidad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblValorCatnidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValorCatnidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCatnidadSolicitada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatnidadSolicitada As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMotivoActivacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMotivoActivacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtTemporal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtTemporal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtPermanente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtPermanente As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtFechaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTituloGrillaServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloGrillaServ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tbServActuales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbServActuales As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLinea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrupoOrigen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrupoOrigen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperador As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ifDocAdjuntos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifDocAdjuntos As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''lblPrevisualizacionCab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrevisualizacionCab As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMensaje As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dvMensajeObligatorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMensajeObligatorio As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMensajeValidCant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeValidCant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMensajeValidTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeValidTipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLimpiarMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpiarMensaje As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMensajeValidTipo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeValidTipo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumWordCaracMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumWordCaracMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divDispSolicitado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDispSolicitado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTipo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaCreacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaCreacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEstadoActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstadoActual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblLineaAmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLineaAmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlanActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlanActual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOperador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblOperadorLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperadorLinea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPlan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfCodPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodPlan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtModeloSeleccionado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModeloSeleccionado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCostoModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCostoModelo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAdvertenciaPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdvertenciaPlan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bnPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bnPlan As Global.VisualSoft.Comun.LibreriaJQ.BarraNavegacionJQ

    '''<summary>
    '''pbnDetallePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbnDetallePlan As Global.VisualSoft.Comun.LibreriaJQ.PanelBarraNavegacion

    '''<summary>
    '''ItemBarraNavegacion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemBarraNavegacion1 As Global.VisualSoft.Comun.LibreriaJQ.ItemBarraNavegacion

    '''<summary>
    '''lblNombrePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombrePlan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMontoTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divSeleccionEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSeleccionEmpleado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MsgConfirmacionAvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgConfirmacionAvance As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMonto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMontoReferencial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoReferencial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNombreFinanc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreFinanc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfIdFInanciamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdFInanciamiento As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMesesCuotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMesesCuotas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMesesCuotas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMesesCuotas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPeriodoGracia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodoGracia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPeriodoGracia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodoGracia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispositivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDispositivoValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDispositivoValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGaleriaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGaleriaTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGaleriaValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGaleriaValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOperadorTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperadorTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOperadorValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOperadorValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAmpPlanActualTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmpPlanActualTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAmpPlanActualValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpPlanActualValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCuentaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCuentaTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCuentaValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCuentaValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPaquetesTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaquetesTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstPaquetesValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstPaquetesValor As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblPaquetesValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaquetesValor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostoTotalTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostoTotalTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCostoTotalValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCostoTotalValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlanesTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlanesTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPlanValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlanValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPlanValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlanValor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblServiciosTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblServiciosTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstServiciosValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstServiciosValor As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblMensajeTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvMensajeValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvMensajeValor As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMensajeValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMensajeValor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMensajeValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeValor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDocAdjuntosTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocAdjuntosTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstDocAdjuntosValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstDocAdjuntosValor As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''lblDocAdjuntosValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDocAdjuntosValor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAmpModeloDispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpModeloDispositivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmpOperado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpOperado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmpLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpLinea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmpPlanActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpPlanActual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAmpPlanes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAmpPlanes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAmpCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmpCuenta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bnAmpPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bnAmpPlan As Global.VisualSoft.Comun.LibreriaJQ.BarraNavegacionJQ

    '''<summary>
    '''pbnAmpDetallePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pbnAmpDetallePlan As Global.VisualSoft.Comun.LibreriaJQ.PanelBarraNavegacion

    '''<summary>
    '''ItemBarraNavegacion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemBarraNavegacion2 As Global.VisualSoft.Comun.LibreriaJQ.ItemBarraNavegacion

    '''<summary>
    '''lblAmpNombrePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmpNombrePlan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAmpMontoTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmpMontoTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoServicioAmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoServicioAmp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlServCuentaTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlServCuentaTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hdfAmpCodServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAmpCodServ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfAmpCodIlimitado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAmpCodIlimitado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddAmpTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddAmpTipoServicio As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblAmpNombreServ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmpNombreServ As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAmpPaquetes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAmpPaquetes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ifInfoFinanciamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifInfoFinanciamiento As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''lblMsjConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjConfirmacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsjConfirmUpdPaquete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjConfirmUpdPaquete As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostExt_Msj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostExt_Msj As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostExt_Det1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostExt_Det1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCostExt_Det2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCostExt_Det2 As Global.System.Web.UI.WebControls.Label
End Class
