'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class P_Movil_Administrar_Imp_RegistroServicio

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfinCodCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfinCodCol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfvcCodCue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfvcCodCue As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodProc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfMesPer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMesPer As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfInTipPla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfInTipPla As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdTipRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdTipRes As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodLinTip_X_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodLinTip_X_User As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TabOpciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabOpciones As Global.VisualSoft.Comun.LibreriaJQ.TabJQ

    '''<summary>
    '''lblSinReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSinReg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFiltroServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltroServicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chklstServiciosSinRegistrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chklstServiciosSinRegistrar As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''imgAsociar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsociar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgSeleccionarTodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSeleccionarTodos As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgLimpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLimpiar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblAregistrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAregistrar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstServicio As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ddlTipoLlamada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoLlamada As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGuardar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCancelar As Global.System.Web.UI.WebControls.Image
End Class
