'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PedidoPlan

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfUsuario As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdUsuarioLogeado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdUsuarioLogeado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEmpleado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdPedidoEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdPedidoEditar As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfFecServidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfFecServidor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfMuestraNumeroContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMuestraNumeroContacto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pDscPreventa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pDscPreventa As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDescripcionTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOperadorTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOperadorTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMontoTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMontoTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''capaPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents capaPopUp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFechaPedi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaPedi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNombreEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreEmpleado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCentroCosto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCentroCosto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoPedido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEstadoPedidoCompra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstadoPedidoCompra As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgCerrarServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCerrarServicio As Global.System.Web.UI.WebControls.Image
End Class
