'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class P_Movil_Conciliar_Documentos

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfLicencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLicencia As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfbtSobreescribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfbtSobreescribe As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfbtPregunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfbtPregunto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfInCodCta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfInCodCta As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfbtTipoPla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfbtTipoPla As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodPla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodPla As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodLinTip_X_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodLinTip_X_User As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdPerfil As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGenerico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGenerico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AccordionJQ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccordionJQ1 As Global.VisualSoft.Comun.LibreriaJQ.AccordionJQ

    '''<summary>
    '''AcordionFiltros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AcordionFiltros As Global.VisualSoft.Comun.LibreriaJQ.ContenedorAccodion

    '''<summary>
    '''dvContenedorFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvContenedorFactura As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bpFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bpFactura As Global.Common_Controles_BusquedaPrincipal_v2

    '''<summary>
    '''btnQuitarFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarFactura As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgQuitarFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuitarFactura As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lstFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstFactura As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''dvContenedorCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvContenedorCuenta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bpCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bpCuenta As Global.Common_Controles_BusquedaPrincipal_v2

    '''<summary>
    '''btnQuitarCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarCuenta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgQuitarCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuitarCuenta As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lstCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstCuenta As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''AcordionFiltros2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AcordionFiltros2 As Global.VisualSoft.Comun.LibreriaJQ.ContenedorAccodion

    '''<summary>
    '''txtPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeriodo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblMensajeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajeConfirmacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfOperador_Origen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOperador_Origen As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtReporteNro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReporteNro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLugar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaReciboSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaReciboSolicitud As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFormalizacionContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFormalizacionContrato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaRecepcionContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaRecepcionContrato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGerencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGerencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubGerencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubGerencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDepartamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContrato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSolpe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolpe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOrdenSurtimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrdenSurtimiento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMontoContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoContrato As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMontoOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMontoOS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPedidoAsociado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPedidoAsociado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRazonSocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRazonSocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtClaveOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaveOperador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRFC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoCargo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoFecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProveedorNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProveedorNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProveedorCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProveedorCargo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProveedorFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProveedorFecha As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConsecutivo01_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsecutivo01_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConsecutivo02_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsecutivo02_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConsecutivo03_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsecutivo03_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLugar_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLugar_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSubDireccion_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubDireccion_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGerencia_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGerencia_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProveedor_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProveedor_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompromisoSAP_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompromisoSAP_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDetalle01_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDetalle01_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartida_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartida_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDetalle02_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDetalle02_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoNombre_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoNombre_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoCargo_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoCargo_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmitidoFicha_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmitidoFicha_BS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPersonalCOPADE_BS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonalCOPADE_BS As Global.System.Web.UI.WebControls.TextBox
End Class
