'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PivotReporteOrganizacional_PorPlan

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblNombreReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreReporte As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ASPxButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton1 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ddlFormatoExportacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFormatoExportacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ASPxButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton3 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ASPxButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton2 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnGuardarComo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardarComo As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnAbrir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAbrir As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDatos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ASPxPivotGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

    '''<summary>
    '''fieldLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldLinea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldIMEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldIMEI As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldMonto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldMonto As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldOperador As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNombreSucursal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNombreSucursal As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldCodCentroCosto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldCodCentroCosto As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldCentroCosto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldCentroCosto As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldGrupoOrigen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldGrupoOrigen As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNivel As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldCodOrganizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldCodOrganizacion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldOrganizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldOrganizacion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldEmpleado As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldNombreCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldNombreCuenta As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldPlan As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldSubPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldSubPlan As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTipoLineaLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTipoLineaLinea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldModeloDispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldModeloDispositivo As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldClasificacionModeloDispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldClasificacionModeloDispositivo As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldEstadoProcesoLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldEstadoProcesoLinea As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''fieldTipoAsignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldTipoAsignacion As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

    '''<summary>
    '''ASPxPivotGridExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPivotGridExporter1 As Global.DevExpress.Web.ASPxPivotGrid.Export.ASPxPivotGridExporter

    '''<summary>
    '''odsOrganizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsOrganizacion As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''hydPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydPeriodo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hydCodEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydCodEmp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hydwhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydwhere As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hydCodInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hydCodInt As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HydFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HydFormato As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlRegionDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionDesde As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRegionHacia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionHacia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTituloNombreReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloNombreReporte As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtplantilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtplantilla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdTipo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdCodReporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCodReporte As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
