'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoginAuthDoble

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfNocerrarSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNocerrarSesion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCaptcha As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomDominio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomDominio As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomIp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomIp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomPc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomPc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomBrowser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomBrowser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUsaDatosConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUsaDatosConfig As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfVerLinkWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfVerLinkWeb As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfVerLinkDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfVerLinkDoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfVerLinkManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfVerLinkManual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTextoLinkWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTextoLinkWeb As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTextoLinkDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTextoLinkDoc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTextoLinkManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTextoLinkManual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUrlLinkWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUrlLinkWeb As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNameDocumentoNormas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNameDocumentoNormas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNameManual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNameManual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfVerCarrusel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfVerCarrusel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsCloud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsCloud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdkstorage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdkstorage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdkstorage_cli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdkstorage_cli As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdTipoDispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdTipoDispositivo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hTiempoConteo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTiempoConteo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hEscena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hEscena As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Expiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Expiro As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdFecLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdFecLocal As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdFecKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdFecKey As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hPresionarReenviado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hPresionarReenviado As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hchkRecordar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hchkRecordar As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hMensaje As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hLimpiarStorage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hLimpiarStorage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pRevisaCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pRevisaCorreo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCod1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCod1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMensajesLic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensajesLic As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnIngresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIngresar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btnReenviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReenviar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''litProductoRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProductoRelease As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCorreo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnRegKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegKey As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
