'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Mnt_SEG_Usuario

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''skinSheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents skinSheet As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodigo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfArchivo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNombreArchivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNombreArchivo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodCliente As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsTecResp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsTecResp As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsResApro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsResApro As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdf_esLDAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_esLDAP As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdf_esAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_esAdmin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdf_idHoras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_idHoras As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdf_flagCargaHorario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_flagCargaHorario As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsllamadaExterna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsllamadaExterna As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdTemporizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdTemporizador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdPerfilTemporizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdPerfilTemporizador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPerfilesOcultos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPerfilesOcultos As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AccordionJQ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccordionJQ1 As Global.VisualSoft.Comun.LibreriaJQ.AccordionJQ

    '''<summary>
    '''txtvcUsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvcUsu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtvcPas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvcPas As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chEditar As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstEmpleado As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmpleado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnQuitarEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarEmpleado As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgQuitarEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuitarEmpleado As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ttgInfoArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttgInfoArea As Global.ToolTipGenerico

    '''<summary>
    '''TextBoxNombreAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxNombreAreas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TextBoxCodigoAreas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBoxCodigoAreas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnAgregarOrga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarOrga As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnQuitarOrganizacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarOrganizacion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtCodSuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodSuc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfCodSucBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodSucBusqueda As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditarCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditarCorreo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''esConfirmPas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents esConfirmPas As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtConfirmacionCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmacionCorreo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblF_vcCodEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblF_vcCodEmp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtF_vcCodEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtF_vcCodEmp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAcceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcceso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUltAcceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUltAcceso As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIntentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntentos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chBloqueo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chBloqueo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBloqueo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBloqueo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chReiniciar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chReiniciar As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tpInfoReinicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpInfoReinicio As Global.ToolTipGenerico

    '''<summary>
    '''lblFecRei control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecRei As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFecUltCla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecUltCla As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''trEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEstado As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEstado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trDobleFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDobleFactor As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkDobleFactor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDobleFactor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblNotaPaginaPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNotaPaginaPrincipal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlNivelProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNivelProducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlPaginaPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPaginaPrincipal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''accOpcionesGenerales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accOpcionesGenerales As Global.VisualSoft.Comun.LibreriaJQ.AccordionJQ

    '''<summary>
    '''lblEsTecResp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEsTecResp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEsResApro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEsResApro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdCodintTecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCodintTecnico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdCodOrgTecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCodOrgTecnico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdNomOrgTecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdNomOrgTecnico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnAgregarOrga2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarOrga2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnQuitaArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitaArea As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hdfIdTecnicoSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdTecnicoSupervisor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtUsuarioSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUsuarioSupervisor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgBuscarUsuarioSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBuscarUsuarioSupervisor As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgBuscarUsuarioSupervisorBorrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBuscarUsuarioSupervisorBorrar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlNiveles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlNiveles As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBolsasParaAsinar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBolsasParaAsinar As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgAgregarBolsa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarBolsa As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgQuitarBolsa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgQuitarBolsa As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlBolsasAsignadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBolsasAsignadas As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''chkAtenciones_EsOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAtenciones_EsOperador As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''hdIdOperadorAtencion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdIdOperadorAtencion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''chkActivarTemporizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActivarTemporizador As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlTemporizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTemporizador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTiempoTemporizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTiempoTemporizador As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkReiniciarTemporizado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReiniciarTemporizado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''imgGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGuardar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.Image
End Class
