'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class P_Movil_Administrar_Mantenimiento_Mnt_Plan

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfCodCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodCliente As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPlan As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSepMiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSepMiles As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTotalLineas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTotalLineas As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodLinTip_X_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodLinTip_X_User As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfImpto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfImpto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tbCamposDinamicos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCamposDinamicos As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''txtPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOperador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ttgInfoEditOpe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttgInfoEditOpe As Global.ToolTipGenerico

    '''<summary>
    '''lblTipoLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoLinea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvTggInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvTggInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ttgInfoTipoLinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttgInfoTipoLinea As Global.ToolTipGenerico

    '''<summary>
    '''ddlLineaTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLineaTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTipoServicio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblMonto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMonto2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkIncImp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncImp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trMontoIncImpuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trMontoIncImpuesto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ttgInfoMontoImpuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttgInfoMontoImpuesto As Global.ToolTipGenerico

    '''<summary>
    '''trManientePlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trManientePlan As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkMantienePlanCamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMantienePlanCamp As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''txtMinAdi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinAdi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgAsociarModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsociarModelo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''chkRoaming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRoaming As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trEstado As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''chkEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEstado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''imgAgregarSubPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarSubPlan As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tbAsignacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAsignacion As Global.VisualSoft.Comun.LibreriaJQ.TabJQ

    '''<summary>
    '''imgGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGuardar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''imgCerrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgCerrar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txt_Dispositivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Dispositivos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfCodDispositivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodDispositivos As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfNomDispositivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfNomDispositivos As Global.System.Web.UI.WebControls.HiddenField
End Class
