'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Adm_ListadoSolicitudes

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdfTituloValeResguardo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTituloValeResguardo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfAdmin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTecnico As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfResApr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfResApr As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfDiaActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDiaActual As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGruTipSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGruTipSol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGruTipSolEdi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGruTipSolEdi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGruTipSolEli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGruTipSolEli As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfSolicitudesMultipleEspecialista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfSolicitudesMultipleEspecialista As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsResponsableDeArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsResponsableDeArea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfResAprTipSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfResAprTipSol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUsuTipSolCre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUsuTipSolCre As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfUsuTipSolEdi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfUsuTipSolEdi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTecResSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTecResSol As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfvcTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfvcTab As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfBusquedaIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfBusquedaIni As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIsAccessAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIsAccessAdd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfIdSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdSolicitud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfdaFechaIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfdaFechaIni As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfdaFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfdaFechaFin As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfCodLinTip_X_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodLinTip_X_User As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfLicencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLicencia As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsAdministradorSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsAdministradorSolicitud As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsResponsableTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsResponsableTI As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsGestorSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsGestorSolicitudes As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfLicenciaModulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfLicenciaModulo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfMostrarOrdenServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfMostrarOrdenServicio As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfEsAutorizador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfEsAutorizador As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TabDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabDetalle As Global.VisualSoft.Comun.LibreriaJQ.TabJQ

    '''<summary>
    '''tblAcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblAcciones As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAgregarMasivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarMasivo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAgregarMasivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAgregarMasivo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tdNoEstandar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdNoEstandar As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''btnMasivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMasivo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgEditar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEditar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnProcesar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProcesar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgProcesar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgProcesar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnSubirFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubirFormato As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnOrdenServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOrdenServicio As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image3 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''dvFormatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvFormatos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnVerDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVerDetalle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgVerDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVerDetalle As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEliminar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgEliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgEliminar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVista As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgVista As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAprobar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAprobar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRechazar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgRechazar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgRechazar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAsignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAsignar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAsignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsignar As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnAsignarA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAsignarA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAsignarA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAsignarA As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnReasignarA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReasignarA As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgReasignarA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgReasignarA As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''btnValeResguardo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValeResguardo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Image5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''eegSolicitudes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eegSolicitudes As Global.ExportarExcelGenerico

    '''<summary>
    '''btnAutDesPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutDesPDF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgAutDesPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgAutDesPDF As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''dvReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvReportes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFiltro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFiltro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFiltro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFiltro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaIni As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpleado As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOrdenServicioFiltro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrdenServicioFiltro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoTec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoTec As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoResApr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoResApr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEstadoApr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoApr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEstadoPro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstadoPro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEspecialista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEspecialista As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRangoFechaIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRangoFechaIni As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRangoFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRangoFechaFin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSolNoVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSolNoVista As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ulListaFormatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulListaFormatos As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ulListaReportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulListaReportes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComentarios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtGeneral As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtPendiente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtPendiente As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtPorAprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtPorAprobar As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtAprobada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtAprobada As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtRechazada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtRechazada As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtPorAsignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtPorAsignar As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtEnProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtEnProceso As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtCulminada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtCulminada As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtAnulada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtAnulada As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtPorAutorizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtPorAutorizar As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtNotasPorRevisar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtNotasPorRevisar As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbtSolicitudesNoVistas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtSolicitudesNoVistas As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblMsjConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsjConfirmacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bpTecRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bpTecRes As Global.Common_Controles_BusquedaPrincipal

    '''<summary>
    '''txtNroOrdenServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNroOrdenServicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoServicio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoMovimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoMovimiento As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDescripcionOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescripcionOS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOrigenSolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrigenSolicitud As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFechaHoraInicioOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaHoraInicioOS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHoraInicioOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoraInicioOS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFactura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNroConsecutivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNroConsecutivo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DropDownList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCosto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCosto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMarca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtModelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNroServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNroServicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIMEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMEI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSIM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPIN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkAccesorios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAccesorios As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''txtObservaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservaciones As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdministradorContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministradorContrato As Global.System.Web.UI.WebControls.TextBox
End Class
